title: "Christina Nguyen"
description: "Christina Nguyen is a UX designer at Nuna in San Francisco."
url: "https://chrnguyen.com"

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
