name: "Christina Nguyen"
description: "My name is Christina Nguyen and I enjoy designing and prototyping products with empathy and moxie."
url: "http://chrnguyen.com"
paginate: 10
markdown: rdiscount
permalink: pretty
gems:
  - jekyll-paginate
